FROM golang:1.20

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y librdkafka-dev 

## COPY . .
##RUN go build -v -o /usr/local/bin/app ./...

##CMD ["app"]
CMD [ "tail", "-f", "/dev/null" ]